name: magjob swagger server handler CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy-to-registry-swagger-server-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
            image: keepitup2023/magjob-swagger-server-handler:latest
            tags: latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
